### ISSUE TITLE
Runtime error when using "counter"

### ISSUE THREAD

**Issue by sdelafond** [pingdomserver/scout-client#41]
I seem to hit a bug with scout, whenever I need to compute a rate. Reporting a plain value works fine, for instance:

```
class DebciPendingCount < Scout::Plugin
  def build_report
    db_file = "/var/lib/debci/data/debci.sqlite3"
    sql = "select count(*) from jobs where status is NULL"
    count = `sqlite3 #{db_file} "#{sql}"`.strip
    report(:pending => count)
  end
end
```

However, the following fails every other time:

```
class DebciProcessed < Scout::Plugin
  def build_report
    db_file = "/var/lib/debci/data/debci.sqlite3"
    sql = "select count(*) from jobs where status is not NULL"
    count = `sqlite3 #{db_file} "#{sql}"`.strip.to_i
    [:hour, :day, :month, :year].each do |period|
      key = "processed_per_#{period.to_s}".to_sym
      counter(key, count, :per => period)
    end
  end
end
```

with:

```
== This plugin doesn't have option metadata.
== You haven't provided any options for running this plugin.
== Output:
{:reports=>[],
 :alerts=>[],
 :errors=>
  [{:plugin_id=>nil,
    :created_at=>"2019-07-22 05:46:16",
    :fields=>
     {:subject=>"Plugin failed to run",
      :body=>
       "RuntimeError: Unknown option for ':per': :hour\n/var/lib/gems/2.3.0/gems/scout-5.9.12/lib/scout/plugin.rb:196:in `counter'\ndebci_processed.rb:8:in `block in build_report'\ndebci_processed.rb:6:in `each'\ndebci_processed.rb:6:in `build_report'\n/var/lib/gems/2.3.0/gems/scout-5.9.12/lib/scout/plugin.rb:222:in `run'\n/var/lib/gems/2.3.0/gems/scout-5.9.12/lib/scout/server.rb:435:in `block in process_plugin'\n/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'\n/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'\n/var/lib/gems/2.3.0/gems/scout-5.9.12/lib/scout/server.rb:434:in `process_plugin'\n/var/lib/gems/2.3.0/gems/scout-5.9.12/lib/scout/command/test.rb:50:in `block in run'\n/var/lib/gems/2.3.0/gems/scout-5.9.12/lib/scout/server.rb:58:in `initialize'\n/var/lib/gems/2.3.0/gems/scout-5.9.12/lib/scout/command/test.rb:48:in `new'\n/var/lib/gems/2.3.0/gems/scout-5.9.12/lib/scout/command/test.rb:48:in `run'\n/var/lib/gems/2.3.0/gems/scout-5.9.12/lib/scout/command.rb:169:in `dispatch'\n/var/lib/gems/2.3.0/gems/scout-5.9.12/bin/scout:9:in `<top (required)>'\n/usr/local/bin/scout:22:in `load'\n/usr/local/bin/scout:22:in `<main>'"},
    :local_filename=>nil,
    :origin=>nil}],
 :summaries=>[],
 :snapshot=>"",
 :config_path=>"/root/.scout",
 :server_name=>nil,
 :options=>[],
 :server_metrics=>{}}
```

"Every other time" is perfectly reproducible: one success, one failure, etc etc. When the run succeeds, everything looks good:

```
== This plugin doesn't have option metadata.
== You haven't provided any options for running this plugin.
== Output:
{:reports=>
  [{:plugin_id=>nil,
    :created_at=>"2019-07-22 05:46:17",
    :fields=>{:processed_per_hour=>nil},
    :local_filename=>nil,
    :origin=>nil},
   {:plugin_id=>nil,
    :created_at=>"2019-07-22 05:46:17",
    :fields=>{:processed_per_day=>nil},
    :local_filename=>nil,
    :origin=>nil},
   {:plugin_id=>nil,
    :created_at=>"2019-07-22 05:46:17",
    :fields=>{:processed_per_month=>nil},
    :local_filename=>nil,
    :origin=>nil},
   {:plugin_id=>nil,
    :created_at=>"2019-07-22 05:46:17",
    :fields=>{:processed_per_year=>nil},
    :local_filename=>nil,
    :origin=>nil}],
 :alerts=>[],
 :errors=>[],
 :summaries=>[],
 :snapshot=>"",
 :config_path=>"/root/.scout",
 :server_name=>nil,
 :options=>[],
 :server_metrics=>{}}
```

I've tried countless variations of my code, but it seems something goes wrong whenever scout tries to a previous locally saved counter; in my development setup, that's from .scout/client_history.yaml, which looks like:

```
---
last_runs:
  Local Plugin: 2019-07-22 01:46:17.536836079 -04:00
memory:
  Local Plugin:
    _counter_processed_per_hour:
      :time: 2019-07-22 01:46:17.560028608 -04:00
      :value: 28807
    _counter_processed_per_day:
      :time: 2019-07-22 01:46:17.560091172 -04:00
      :value: 28807
    _counter_processed_per_month:
      :time: 2019-07-22 01:46:17.560107029 -04:00
      :value: 28807
    _counter_processed_per_year:
      :time: 2019-07-22 01:46:17.560121395 -04:00
      :value: 28807
last_client_key: 
```

This happens using scout 5.9.12 with ruby 2.3.3.

**Comment by barlima** [comment]
hi @sdelafond, sorry for the late response.
The counter accepts only `:second` and `:minute` as `:per` value:
https://github.com/pingdomserver/scout-client/blob/7aef6641c91975841ae687f737fbe6babc75a65d/lib/scout/plugin.rb#L190-L197

**Comment by sdelafond** [comment]
@barlima thanks a lot of the answer. Would you consider https://github.com/pingdomserver/scout-client/pull/42 ?
